### ISSUE TITLE
Array Concatenation

### ISSUE THREAD

**Issue by darrenscerri** [Chalarangelo/30-seconds-of-code#108]
`const ArrayConcat = (arr, ...args) => arr.concat(...args); ` is useless in the sense that it's not doing any valuable work, it's wrapping a function, leaving the exact same behaviour. `Array.concat()` doesn't mutate the array.

Also, the example result is wrong.

**Comment by Chalarangelo** [comment]
I didn't test, I though it was working, seemed simple enough. The idea was to duplicate lodash's [`concat`](https://lodash.com/docs/4.17.4#concat) behavior. Any suggested fixes or improvements?

**Comment by Chalarangelo** [comment]
Ok, I just fixed the example to show what it should.

**Comment by darrenscerri** [comment]
Right, the only advantage of Lodash's `concat` is safety. `arr` can be a non-array value and the function would not throw an error. The `ArrayConcat` examples doesn't provide this safety, so essentially it is identical to `Array.concat` in terms of behaviour, functionality and safety.

**Comment by Chalarangelo** [comment]
Great point! I am reading lodash's `concat` and I see what you mean. We should improve our `arrayConcat` to provide the same functionality. PR anyone?

**Comment by skatcat31** [comment]
So what I'm hearing is that we want a ternary to type check for `.concat()`?

**Comment by Chalarangelo** [comment]
@skatcat31 sounds like it! If you want/can, PR it at some point. I want this resolved asap.

**Comment by sabareeshkk** [comment]
@darrenscerri  this will do the trick right?
 `const arrayConcat = (arr, ...args) => [].concat(arr, ...args);`
this creates a new array and no error thrown the arr is not an array

**Comment by skatcat31** [comment]
@sabareeshkk 
```js
arrayConcat({}, {}) // [{},{}]
```

There are many other odd edge cases with that sort of thing. maybe just let it crash. If the developer tried to concat something without type checking it, wouldn't the best option be to let the error bubble in proper design?

**Comment by darrenscerri** [comment]
To be honest, don't think adding safety to native APIs is the scope of this repo. Thoughts @Chalarangelo ?

**Comment by Chalarangelo** [comment]
I wrote the snippet to implement lodash's `concat` which in itself is something between a polyfill and a method that deals with some corner cases. I wouldn't mind keeping the improved snippet, just to showcase the technique, but we might not actually need it in the long run. I'll probably merge the PR with the change and let it sit for a while untagged while we discuss this further.

**Comment by Chalarangelo** [comment]
This was resolved (as far as I can tell) in #148.
