### ISSUE TITLE
Node.js snippets

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/30-seconds-of-code#121]
In reference to #120, where do we stand on Node.js snippets? I think we should get the tagging and categories working first before we add Node.js snippets, to distinguish from browser-specific ones. What do you guys think?

**Comment by elderhsouza** [comment]
I'm actually all for it!
I think that node snippets have some different use cases than js in the browser, I'm talking about FS, IO workflows for example, so yeah. I think it's a great idea. 👍

**Comment by Chalarangelo** [comment]
@elderhsouza I agree, there's a ton of node-specific things I would like to see on the list, but I'd like to get the tagging script written first to make sure we get that sorted beforehand. Maybe we should discuss what categories we need under #94 ?

**Comment by elderhsouza** [comment]
@Chalarangelo Right, I think we can close this then.
