### ISSUE TITLE
Round Number To n Digits

### ISSUE THREAD

**Issue by ecwyne** [Chalarangelo/30-seconds-of-code#133]
Wanted to gauge interest before creating a PR. Would others consider this clear & useful?

```javascript
const round = (n, decimals = 0) => Number(`${Math.round(`${n}e${decimals}`)}e-${decimals}`)
```

Importantly the above works correctly with all floating point numbers.

```javascript
// All of the following *should* return 1.01 but *actually* return 1

Number(1.005.toFixed(2))
Math.round(1.005 * 100) / 100
```

**Comment by Chalarangelo** [comment]
Hi, thanks for the interest! I like the idea, was planning to add something like what is mentioned on [this SO thread](https://stackoverflow.com/q/11832914/1650200). Basically, round the number only if necessary and omit trailing zeroes. Do you think you can code that, so we can add it?

**Comment by ecwyne** [comment]
Of course @Chalarangelo!

The current implementation has the type signature `(Number, Number?) => Number` so it already only rounds if necessary and omits trailing zeroes (Numbers don't have trailing zeroes)

If you wanted `(Number, Number?) => String` you can easily just call `.toString()` on the result

**Comment by Chalarangelo** [comment]
@ecwyne get cracking, we should get this added! 😉
