### ISSUE TITLE
console.log usage in time taken by function

### ISSUE THREAD

**Issue by skatcat31** [Chalarangelo/30-seconds-of-code#134]
console.log... ah how we both love an hate you.

Realistically you might not want to use console.log unless you want `stdout/1` to see the text. There are other console channels that exist for that exact purpose on console. Since this is more of a debugging tool you'd want to remove from code before pushing, it might also be better to be able to bypass it.

Marking as an issue for coding later when I'm off work 😉

**Comment by Chalarangelo** [comment]
I'm not well-versed in the `console` channels to be honest. PR it when you can, I'll merge it!

**Comment by atomiks** [comment]
You can use `console.time()` as well.

```js
const perf = callback => {
  console.time('perf');
  const res = callback();
  console.timeEnd('perf');
  return res;
};

perf(() => {
  Array(1000000).fill(0).map(Math.random)
});
// perf: 164.376953125ms
```

**Comment by Chalarangelo** [comment]
@atomiks not a bad idea honestly!

**Comment by skatcat31** [comment]
Hey somebody picked it up! atomiks, you should PR that!

**Comment by skatcat31** [comment]
Hey somebody picked it up! @atomiks , you should PR that!

**Comment by Chalarangelo** [comment]
This was resolved, so I'm closing.
