### ISSUE TITLE
Add arrar.sort() to the method of dropElements 

### ISSUE THREAD

**Issue by supperjet** [Chalarangelo/30-seconds-of-code#147]
The array method of dropElements seems that can not get correct result as the array is unordered.
like this: dropElements([4, 2, 3, 4, 5], n=> n>=3) -> [4,2,3,4,5 ]
 
so
```
const dropElements = (arr, func) => {
     arr.sort();
     ....
}```
is better

**Comment by Chalarangelo** [comment]
Drop doesn't work like that. It goes through the array removing the first element each time until the function returns true. There are plenty of use-cases where you need this and it is not numeric array specific at all. It might be the example that's confusing Consider this, instead:

```js
// dropElements(['a','cool','cat'], n => n === 'cool') -> ['cool','cat']
```

In this case, we want to cut anything before the word cool. 

I'm closing as I believe this was based on a misunderstanding of what the snippet did, but feel free to comment if you want and we can discuss this further.

**Comment by supperjet** [comment]
Haha, I really misunderstanding the snippet. Thanks for you detailed explanation. Impressive, I can not wait to try other method.
