### ISSUE TITLE
Capitalize: lowercase the rest of the string?

### ISSUE THREAD

**Issue by proustibat** [Chalarangelo/30-seconds-of-code#16]
We could maybe consider that if we call capitalize on a string, we expect the first letter to be uppercase but the rest to be in lowercase ?
I suggest we could add it as follows: 
`var capitalize = str => str[0].toUpperCase() + str.slice(1).toLowerCase();`

or with a default option as follows:
`var capitalize = (str, lowerRest=true) => str[0].toUpperCase() + (lowerRest ? str.slice(1).toLowerCase() : str.slice(1));`

**Comment by Chalarangelo** [comment]
Good idea! I prefer the default option idea, as it is more like progressive enhancement for the snippet. I would also argue that `lowerRest` should default to `false`, to avoid confusion, but I might be in the minority here.

**Comment by Chalarangelo** [comment]
Just added this to the existing snippet. Thanks for the idea!
