### ISSUE TITLE
Digitize (variadic)

### ISSUE THREAD

**Issue by meetzaveri** [Chalarangelo/30-seconds-of-code#160]
https://github.com/Chalarangelo/30-seconds-of-code#number-to-array-of-digits 
### Here I found out one bug/caveat! Compare these two code,
```
//first code 
const digitize = n => (''+n).split('').map(i => parseInt(i));
// digitize(2334) ->  (4) [2, 3, 3, 4]
```
```
//second code
const digitize = n => (''+n).split('').map(i => parseInt(i));
//   digitize(2,3,3,4) -> [2] 0:2
```
So here's the bug where user wants to input in separated manner with ',' then function will not work. Also in first code, user wants to insert multiple values which has more than two digits then,
```
digitize(23,232,3424);
//(4) [2, 3, 3, 4]
```
So definitely depends how user inputs. So we should write in desc. that user should enter input in specific manner so that it returns as pure

**Comment by Chalarangelo** [comment]
Isn't the `digitize` function supposed to take just one argument? I mean we can convert it to work with variadic arguments, but I am not sure this is necessary. Opinions?

**Comment by meetzaveri** [comment]
But what if user needs to input two digit numbers? Then it will not work as third snippet in issue is!

**Comment by Chalarangelo** [comment]
The function signature indicates that only one argument should be passed. If we want to convert to a variadic function, we should do something like (off the top of my head, test this):

```js
const digitize = (...args) => ['',...args].join('').split('').map(i => parseInt(i));
```

That one should work for variadic arguments.

**Comment by meetzaveri** [comment]
Then also whole two digit number is not going to be selected in array.
```
const digitize = (...args) => ['',...args].join('').split('').map(i => parseInt(i));
digitize(12,123,1234);
// (9) [1, 2, 1, 2, 3, 1, 2, 3, 4]
```

**Comment by Chalarangelo** [comment]
Not at all, the result is exactly as intended. It's suppose to split a number (or numbers) into an array of digits.

**Comment by meetzaveri** [comment]
I thought it should be like supporting two digit value also.

 No problem if the main reason is to split out a single digit number.

**Comment by Chalarangelo** [comment]
The original idea was to split one number into digits (which has valid use-cases as far as I can tell, had to do this in the past). I don't know if we *have* to make this variadic, as I can't remember the last time I had to digitize a bunch of numbers in the same array, plus you can digitize multiple values by sticking them in an Array and calling `Array.map()` so I vote we keep as-is.

**Comment by meetzaveri** [comment]
Okay got it ! 
sure you can now close this!
