### ISSUE TITLE
Deep flatten array

### ISSUE THREAD

**Issue by accforgit** [Chalarangelo/30-seconds-of-code#163]
(''+[1,[2],[[3],4],5]).split(',').map(x=>+x) 
-->[1, 2, 3, 4, 5]

**Comment by Chalarangelo** [comment]
That only applies for numbers and is sort of a JS side-effect. It's entirely unsafe to use for other values.

What happens is that the inside array is parsed as a string, then converted to a number. Too implicit and can cause all kinds of problems.
