### ISSUE TITLE
Array difference

### ISSUE THREAD

**Issue by anteriovieira** [Chalarangelo/30-seconds-of-code#168]
Should not the difference be verified on both sides?

```js
// difference([1,2,3], [1,2]) -> [3]
// or 
// difference([1,2], [1,2, 3]) -> [3]
```

**Comment by prodigic** [comment]
i have an update for the symmetric difference. in set theory, difference is more link 'not in'

**Comment by skatcat31** [comment]
We should really call that one more `Set Difference` than array difference. In fact it might be a good idea to convert the `Array`s to `Set`s and use their difference mechanisms for a more defined idea

**Comment by Chalarangelo** [comment]
@skatcat31 that's a good idea. @prodigic I have suggested that we split into different snippets in #155. Get on that if you can, so I can merge it.
