### ISSUE TITLE
Update to Contribution Guidelines on Error Handling

### ISSUE THREAD

**Issue by skatcat31** [Chalarangelo/30-seconds-of-code#172]
I saw this question pop up in Gitter, and while Gitter is a great place to chat, a documented approach to the decision should be used for such a wide reaching impact.

As it stands the guidelines don't contain any rules for handling errors. We should make sure that contributions know what they should do with errors. As I see it there are two possible ways forward(that are also non exclusive):

 - unless a function has an exact reason to handle an error(a `Maybe` Monad), that it should let the error bubble
 - a function should handle very specific obvious errors, and throw on all others

Best practices state:
> Errors, unless obvious to be handled at that scope, should always bubble to the place that called the handler. It is up to the developer to make sure they know what errors can happen and what to do with them. Often times it is actually in best interest to let a program fail on an Error being thrown if it would put the program into an unknown state, and being safe is ALWAYS better than being "stable"

The contribution guidelines should be updated so that people don't try to submit `Maybe Monad`s without knowing what they're doing.

For those that don't know what a `Maybe Monad` is:

```js
const Maybe = fn => ( ...args ) => { try{ fn( ..args ) }catch( e ){ return; } } // returning null is also seen as correct, however in many cases a null may be a sought after value
```

**Comment by Chalarangelo** [comment]
I believe we should update the guidelines to state that it is not necessary to handle errors unless there is some important reason to. Otherwise, we will end up with so much bloat and unmaintainable code if we try to error handle everywhere.

I also suggest we add a few methods for sanitization if we can.

**Comment by Chalarangelo** [comment]
So far we were not handling wrong input in functions and we will not start doing so, as it will add significant overhead to everything. I updated the guidelines to specify that errors in input should not be handled unless absolutely necessary. Feel free to improve the wording if it's not great.
