### ISSUE TITLE
Flatten is slow

### ISSUE THREAD

**Issue by kirilloid** [Chalarangelo/30-seconds-of-code#173]
Flatten now works in O(N^2), because of constantly re-creating and copying already accumulated part.

`const flatten = arr => [].concat(...arr)` is much faster on larger arrays.

This implementation is subjected to StackOverflow if original array contains tens of thousands items.

**Comment by kirilloid** [comment]
There are snippets already subjected to the same problem, e.g. `Math.max(...arr)`

**Comment by skatcat31** [comment]
This is a fair point. I hadn't looked at the `flatten()` snippet yet, but O(N^2) is usually reserved for very specific use cases(sorts, searches) and as such means that it should probably be addressed. Your provided snippet of

```js
const flatten = arr => [].concat(...arr)
```

looks about right in terms of big O and avoids using any complicated memory tricks with comma operators. The only problem is it causes the stack to blow up. I'm not certain the alternate is better in terms of speed, but does reduce suffer from stack issues?

```js
const flatten = arr => arr.reduce( ( a, v ) => Array.isArray( v ) ? a.concat( v ) : a.push( v ). [ ] )
```

**Comment by kirilloid** [comment]
Push returns length instead of just `this`

**Comment by kirilloid** [comment]
Unfortunately there’s no concise, fast and large arrays-tolerant solution for that problem.
It’s either slow, or can blow up or is big and clumsy

**Comment by skatcat31** [comment]
well unless we want to use comma operators, it looks like I'll have to update my snippet to use a full function body with semis

```js
const flatten = arr => arr.reduce( ( a, v ) => { Array.isArray( v ) ? a.concat( v ) : a.push( v ); return a; }, [ ] )
```

**Comment by Chalarangelo** [comment]
Pretty much any array method that works through 100k elements will break down, so we can't do a lot about it, except eventually add a disclaimer. (There will be a separate issue to discuss this as a general guideline). I'm closing this issue for now, as we can't really do a lot about this, apart from accept that JS has its quirks.

**Comment by kirilloid** [comment]
So here's a (seemingly) fast, robust, but not beatiful solution.
```javascript
const chunkedEach = (arr, fn, size = 10000) => {
  for (let i = 0; i < arr.length / size; i++) {
    fn(arr.slice(i * size, (i + 1) * size));
  }
};
const flatten = arr => {
  const result = [];
  arr.forEach(a => {
    if (Array.isArray(a)) {
      chunkedEach(a, sub => result.push(...sub));
    } else {
      result.push(a);
    }
  });
  return result;
);
```
