### ISSUE TITLE
Why Array.reduce() is needed in Array remove when we can get the same result using just Array.filter()? 

### ISSUE THREAD

**Issue by vivek28111992** [Chalarangelo/30-seconds-of-code#179]
Why array reduced is used?

`const remove = (arr, func) => 
	Array.isArray(arr) ? arr.filter(func).reduce((acc, val) => {
		arr.splice(arr.indexOf(val), 1);
		return acc.concat(val); 
	}, [])
	: [];`

as we can get the same result using this

`const remove = (arr, func) => 
	Array.isArray(arr) ? arr.filter(func)
	: [];`

Can anyone please answer this?

**Comment by Chalarangelo** [comment]
This is done to remove duplicate elements from the final result.
