### ISSUE TITLE
Swap values of two variables

### ISSUE THREAD

**Issue by fejes713** [Chalarangelo/30-seconds-of-code#182]
This is not a function really. It's just a tip on how to swap values of 2 variables. However, it is really useful for someone who is new to ES6 syntax. 

Both @Chalarangelo  and me think that _30-seconds-of-code_ should be **consistent** and focus only on functions and with that in mind `swap values of two variables` doesn't really fit in here. 

What do you think about the whole situation with it? Should we keep it?

**Comment by Chalarangelo** [comment]
Like I said on gitter, we should probably remove it. It's a useful tip, but we want functions to work as-is (and be functions actually), so I suggest we get rid of it.

**Comment by fejes713** [comment]
I taught about making a function that does it but it doesn't make sense since syntax already allows for it very easily. I also think we should remove it.

**Comment by Chalarangelo** [comment]
Ok, I'm closing and removing the snippet. We should be fine with that.
