### ISSUE TITLE
JSON to Date

### ISSUE THREAD

**Issue by kirilloid** [Chalarangelo/30-seconds-of-code#191]
I have no idea where did you get that format "/Date(_timestamp_)/", but 
`new Date().toJSON()` returns an ISO representation like `2017-12-16T18:16:36.514Z`

Also instead of manually formatting a date, you can use [toLocaleDateString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString#Browser_compatibility), which is supported literally in every browser in its basic form.

**Comment by Chalarangelo** [comment]
Uhm, I can't remember who PRed that, maybe they know where that came from. 😅

**Comment by fejes713** [comment]
@Chalarangelo I PRed fixed function that **someone else made**. Cannot remember who did it but it was in the last 24hours I think.

**Comment by fejes713** [comment]
#152 I found it. I just made it more ES6 friendly didn't check much on the functionality.

**Comment by Chalarangelo** [comment]
I didn't check that but I don't think I have seen that in my life before. @sekmenhuseyin could you explain a bit further where such data would come from?

**Comment by fejes713** [comment]
I am not sure but he mentioned it comes from ajax req.

**Comment by sekmenhuseyin** [comment]
For example: 
I have a table with a date column in it. I send this table from controller to view with jsonresult. thanks to json serializer, these date column datas change. To read this data we need to use a javascript format function.

**Comment by Chalarangelo** [comment]
I have honestly never seen this before, but if you say so, I think we should keep the current implementation. Anybody objecting to that decision?

**Comment by ShirtlessKirk** [comment]
That's an old (but obviously still in use) Microsoft AJAX response. There is no Date literal in JavaScript (and hence JSON) so the onus is on the developer to verify that the response is correctly formed - as it is with newer implementations - and either transform the value before encoding, if possible, or afterward with a client-side function.

This does mean that you have to know what the data type of a particular point is supposed to be...

**Comment by kirilloid** [comment]
I think that this snippet a good example of how to parse a custom Date serialization.
I will create a PR with `toLocaleDateString` instead of hand-written solution bound to a specific locale (UK?)

**Comment by ShirtlessKirk** [comment]
@kirilloid see https://weblog.west-wind.com/posts/2014/jan/06/javascript-json-date-parsing-and-real-dates

There's a function that deals with Microsoft date-constructors-as-strings-in-JSON in that page.

**Comment by kirilloid** [comment]
@ShirtlessKirk I think some points in this article are obsolete. E.g. parsing ISO time representation is supported OOTB with native `Date.parse` and is a trivial thing.
But the whole goal of this project as I understand it is about to show how to do some non-trivial things. W/o even thinking to certain format mentioned here, the snippet is a good demonstration on how to handle that..

**Comment by sekmenhuseyin** [comment]
you can look here: https://stackoverflow.com/questions/206384/how-do-i-format-a-microsoft-json-date

**Comment by Chalarangelo** [comment]
Alright, I think the snippet's usefulness has been justified and the question answered, so I'm closing the issue. If anyone wants to submit a PR with improvements or anything like that, feel free to do so!
