### ISSUE TITLE
isArray has unnecessary code

### ISSUE THREAD

**Issue by kirilloid** [Chalarangelo/30-seconds-of-code#192]
Why do we need that extra `!!`?
```javascript
[false, null, undefined, NaN, 0, ''].filter(Array.isArray)
```
is empty, no falsy value is considered as an array

Maybe, I can create a PR with several such small changes instead of writing about every separately?

**Comment by Chalarangelo** [comment]
To convert to a boolean value. This was mentioned before and was actually PRed to fix the issue of the return value not always being boolean.

**Comment by kirilloid** [comment]
But you don't need `!!val` part at all! Just use `Array.isArray`

**Comment by Chalarangelo** [comment]
You need it to check if the array is empty or something like that.

**Comment by kirilloid** [comment]
No, it is not needed.
There are only six falsy (which result in `false` when converted to Boolean, e.g. with `!!`) values in JavaScript, all enumerated in my first comment.

**Comment by dfdeagle47** [comment]
To add more context, the PR in question is https://github.com/Chalarangelo/30-seconds-of-code/pull/130 which fixes https://github.com/Chalarangelo/30-seconds-of-code/issues/111, i.e.
```
const isArray = val => val && Array.isArray(val);
// isArray(null) -> null (not false)
```

which was changed to

```
const isArray = val => !!val && Array.isArray(val);
// isArray(null) -> false
```

However, as @kirilloid just said, the first part of the expression is unneeded, it should read
```
const isArray = val => Array.isArray(val);
```

Unless I'm unaware of some implementation difference between different engines, `Array.isArray()` always returns a boolean value, and correctly works with the different falsy values.

**Comment by Chalarangelo** [comment]
@dfdeagle47 there's actually some controversy regarding this particular snippet, as there is a slight chance we might remove it entirely iff we only need to check `Array.isArray()`, so until we figure that out it might be irrelevant making changes in case we delete it in the end.

**Comment by dfdeagle47** [comment]
@Chalarangelo : ok makes sense now, I didn't know that part of the discussion.
