### ISSUE TITLE
() instead of _ for functions with no parameters.

### ISSUE THREAD

**Issue by Kladdkaka** [Chalarangelo/30-seconds-of-code#208]
Hi!

First of, thanks for this! It looks amazing and really helpful! 👍 

I am just wondering why the convention is to use `_` for functions with no parameters, instead of the official `()` :)?

I would like to change it, I could make a push request to change all occurances of it, if I just get a yes :)

Cheers in advance,
Erik

**Comment by Chalarangelo** [comment]
To be honest, using `_` is harder to read than `()` and I have wanted to change this for a little while. If you can submit a PR fixing all occurences, that would be pretty cool. Please remember to also update line 58 of the CONTRIBUTING.md in the same PR, for consistency.

**Comment by Kladdkaka** [comment]
Alright! I will do that :) Thank you!

Will send you a pull request in 30 minutes or so!

**Comment by Chalarangelo** [comment]
Great, glad someone can deal with that! 👍 

I'm closing the issue and awaiting for your PR!
