### ISSUE TITLE
pull snippet does not work

### ISSUE THREAD

**Issue by AlexOldest** [Chalarangelo/30-seconds-of-code#214]
Original version of **pull** snippet does not work. The following version works but returns a new array.
```javascript
const Pull = (a, ...args) => { const s = new Set(args); return a.filter(x => !s.has(x)); };
let a = ["I", "see", "the", "present", "and", "the", "past"];
let v = Pull(a, "the", "and");  // ["I", "see",  "present", "past"]
```

**Comment by Chalarangelo** [comment]
This was just fixed in #213. If you do not want to mutate the array, you should use the array without snippet, by the way, as the pull snippet is supposed to mutate the array.
