### ISSUE TITLE
Browser —— bottomVisible  error

### ISSUE THREAD

**Issue by supperjet** [Chalarangelo/30-seconds-of-code#217]
there is a error in the method of bottomVisible. 

it should be `document.body.clientHeight`, not `document.documentElement.clientHeight`

````
const bottomVisible = () => {
    return (document.documentElement.clientHeight + window.scrollY) >= (document.documentElement.scrollHeight || document.body.clientHeight)}
```

**Comment by Chalarangelo** [comment]
I think I tested that and it worked, but you might be onto something. Let me get back to you!

**Comment by Chalarangelo** [comment]
After retesting, this works as expected and it seems like `documentElement` is more reliable than `body` on certain older browsers.
