### ISSUE TITLE
I have a contribution...

### ISSUE THREAD

**Issue by grantmx** [Chalarangelo/30-seconds-of-code#219]
But it seems that I cant submit a pull request.  Can I join the gang?  ;)

"You may not have permission to access 30-seconds-of-code."

**Comment by Chalarangelo** [comment]
As far as I can tell anyone can submit PRs, this is very weird. Anyone else have this problem? 

The more the merrier, I want to get as many people as possible onboard! Welcome to our little community! 😄

**Comment by grantmx** [comment]
Thanks!  Not 100% sure what I'm doing wrong.  I'll keep trying.

**Comment by Chalarangelo** [comment]
I see you opened a PR in #220, I'll be with you shortly! 👍
