### ISSUE TITLE
Alfredsnippets Support

### ISSUE THREAD

**Issue by lslvxy** [Chalarangelo/30-seconds-of-code#235]
I have create an .alfredsnippets file which you can then be imported into Alfred 3.

here is the link,and i will add es5 snip later

[30-seconds-of-code-alfredsnippets](https://github.com/lslvxy/30-seconds-of-code-alfredsnippets)

Could you add this to your README file

**Comment by Chalarangelo** [comment]
Hi, what exactly is alfredsnippets? First time I hear of it.

**Comment by elderhsouza** [comment]
Hi @lslvxy 

I have used Alfred in my time with OSX, it's a great piece of software, that's basically a launcher bar to a whole lot of features, think Sublime's command pallete for your entire OS.

https://www.alfredapp.com/

I think it's great to integrate this project with other tools, I have not tested this plugin yet, and I also think tis might open a precedent to integration tools in the project, I think this might be a good discussion.

@Chalarangelo Maybe add it just like @lslvxy suggested, create a section in the README? What do you think?

**Comment by skatcat31** [comment]
Wait if I'm reading this correctly it's just a bookmark for Alfred that would open up the repo in a browser?(Sorry for the ignorance, I'm a windows user)
____
### After thoughts
Huh when I used MacOS years ago alfred looks a lot like an app I used. Guess power launchers are still sought after. I'm on windows so I just press `START` and begin typing to use the search functions XD

**Comment by lslvxy** [comment]
Alfred just work on MacOS 

It is a code Snippets , just like [TextExpander](https://smilesoftware.com/textexpander).
<img width="611" alt="default" src="https://user-images.githubusercontent.com/5688054/34135062-4b271c82-e499-11e7-9810-224d98930289.png">

 You can quickly enter the code with snippets.

**Comment by Chalarangelo** [comment]
Well, I have no reason to refuse so I will add a link in the README and close the issue in a bit. 👍
