### ISSUE TITLE
Add output exemple bellow, or as i call it, the noob helper

### ISSUE THREAD

**Issue by renatodeleao** [Chalarangelo/30-seconds-of-code#24]
# Context
Thanks for putting this together, i've personally used a few (that took me some serious stackoverflow thread search time).

I'm a terrible developer, but i'm a curious guy. Coming from a design background, i'm more of a visual learner. Sometimes the english description might not be enough to understand some examples of this repo, as I could not understand some terms :man_shrugging:

So my current flow is more or less like this:

![flow](https://d26dzxoao6i3hh.cloudfront.net/items/121d0h3D061Q362C3o02/%5Bb682a177ac640029da9b8bd5f8d1838d%5D_Image+2017-12-12+at+10.13.21+AM.png?v=cbb7beff)

## Question
So in relevant cases,  would it be helpful for anyone else to include a usecase commented bellow like the [filter-out-non-unique-values-in-an-array](https://github.com/Chalarangelo/30-seconds-of-code#filter-out-non-unique-values-in-an-array) exemple?

```javascript
const unique = arr => arr.filter(i => arr.indexOf(i) === arr.lastIndexOf(i));
// unique([1,2,2,3,4,4,5]) -> [1,3,5]
```

Props for this 👍 , I might even submit a PR with a snippet one these days, who knows?!

**Comment by Chalarangelo** [comment]
Examples like the one you mentioned are definitely going to be added, I just haven't had the time to get to that yet. I have had to deal with something like 20 PRs since I woke up, a rough draft for the styleguide and a few other things. Hang in there, examples for all snippets and polishing should be up and running by tonight. 😉

**Comment by renatodeleao** [comment]
@Chalarangelo wow that was fast! Now worries and take your time! 
It's just as small enhancement as 90% of the examples are actually understandable under 30secs, even for me x)

Keep shipping :shipit:

**Comment by Chalarangelo** [comment]
All snippets have been updated.
