### ISSUE TITLE
[BUG] Code snippets don't appear on mobile

### ISSUE THREAD

**Issue by Daniel15** [Chalarangelo/30-seconds-of-code#243]
## [BUG] Code snippets don't appear on mobile
Load https://chalarangelo.github.io/30-seconds-of-code/ on Chrome Android, or in the mobile emulation view on Chrome (on desktop)
Scroll down
Notice that the code snippets do not appear:
![](https://d.sb/2017/12/chrome_18-11.55.58.png)

**Comment by Youngestdev** [comment]
That should be a network error i guess. Have you tried refreshing the page ?

**Comment by Daniel15** [comment]
Yeah, several times. It works fine in Chrome on my laptop, but breaks as soon as I switch to mobile emulation in the dev tools.

**Comment by skatcat31** [comment]
Cannot confirm on Chrome, Firefox, Chrome Mobile Emulator, Firefox Mobile emulator, Chrome(Mobile), Samsung Browser(Mobile). What version of Chrome and Chrome Mobile are you using?

**Comment by skatcat31** [comment]
Deleted previous comment, have reliably reproduced the error on all browsers.

Can confirm on certain functions code does not appear, and on some functions code will appear after scrolling the code box. It seems to be sporadic which ones don't want to work and which do, and consistent for some functions.

**Comment by taltmann42** [comment]
Apparently, adding `transform: scale(1)` to the `code` elements fixes the bug in Chrome (probably different render handling, not sure?). Can others having the problem confirm that - I wasn't able to reproduce the bug in Safari or FF?

**Comment by Pl4gue** [comment]
@Daniel15 Thanks for sharing the issue! We will fix that :wink:

**Comment by Chalarangelo** [comment]
This is most likely a bug with my CSS framework (I'm using the latest alpha, so this might be something I have overlooked). I'll see what I can do. @taltmann42's suggestion sounds promising. I'll test and see if it works.

**Comment by fejes713** [comment]
@taltmann42 I can confirm. Happens on my android in Chrome. We will fix it.
