### ISSUE TITLE
Translations (Chinese)

### ISSUE THREAD

**Issue by hxl9654** [Chalarangelo/30-seconds-of-code#247]
Is there any plan to translate to Chinese? I can help.

**Comment by Chalarangelo** [comment]
Translations, in general, would be a really cool thing to add, however I feel like this will require dedicated teams of translators for each language and I'm pretty sure it's quite difficult keeping track of all the snippets being added over time.

**Comment by fejes713** [comment]
As the project grows this would definitely be a good idea. For now, I think it's going to be really hard to keep track of everything. Accessibility for everyone is in general awesome idea. Maybe not now, but in the future we could make that happen for sure.

**Comment by hxl9654** [comment]
OK, @me if you need any help in the future.

**Comment by fejes713** [comment]
@Chalarangelo you can close this one I guess. We won't be doing this anytime soon, am I right?

**Comment by Chalarangelo** [comment]
I think so, we should open a call for translators sometime in January or February I suppose. Closing this one for now!

**Comment by daGaiGuanYu** [comment]
I can do sth on translation job if you need.

**Comment by fejes713** [comment]
Thanks for letting us know @daGaiGuanYu, we do really appreciate it. I do not think we need translators at this moment due to to the scale of the project. 

We could only start something like Chinese version if you will commit 101% of your time to fully translate and maintain the Chinese version. Right now, at this scale, I don't think anyone would be interested in committing that much time.

**Comment by Chalarangelo** [comment]
I agree with @fejes713. I tried translating to Greek at some point and it was impossibly difficult to accomplish and maintain. If you want to do a separate Chinese version, we would happily link it from the README as an unofficial project.

**Comment by daGaiGuanYu** [comment]
K,,,,thanks for your reminding @Chalarangelo @fejes713, just in case you need form a team for translation in the future.

**Comment by fejes713** [comment]
Sure! We will keep you in the loop if we ever decide to translate this with a bigger team. Thank you anyways! 👍
