### ISSUE TITLE
shuffle方法有问题

### ISSUE THREAD

**Issue by wjjhhh** [Chalarangelo/30-seconds-of-code#251]
const shuffle = arr => arr.sort(() => Math.random() - 0.5);
这个并不是真正的随机

**Comment by Artoria** [comment]
LMTTFY: that's not really random

**Comment by Chalarangelo** [comment]
This has been mentioned before and we have tried a lot of different things. It's not truly random, but it works well enough. For reliable shuffling in an array, you probably need a really robust snippet which at this time we do not have. If anyone wants to submit a PR with a Fisher-Yates implementation, I would gladly merge it.

**Comment by atomiks** [comment]
Here is an implementation: https://bost.ocks.org/mike/shuffle/

Pure + ES6-ified:
```js
const shuffle = arr => {
  arr = [...arr];
  let m = arr.length;
  while (m) {
    const i = Math.floor(Math.random() * m--), t = arr[m];
    arr[m] = arr[i], arr[i] = t;
  }
  return arr;
};
```

**Comment by Chalarangelo** [comment]
@atomiks that seems alright, but I think we should keep the previous shuffle, too. Maybe we should rename the original `shuffle` to `randomizeOrder `(and add in the description that it is not truly random) and keep your implementation as `shuffle`. That way we demonstrate a technique that is commonly used and explain that it is not the best (but still works if you want to do some simplistic shuffling that you don't care about too much), while we also have a more powerful algorithm for pretty good shuffling for those who need it.
