### ISSUE TITLE
[Suggestion] website contribution guidelines

### ISSUE THREAD

**Issue by arjunmahishi** [Chalarangelo/30-seconds-of-code#275]
[Contribution guide](https://github.com/Chalarangelo/30-seconds-of-code/blob/master/CONTRIBUTING.md) doesn't have any guidelines on how to contribute to the website. Also, instructions are needed on how to run the website locally and debug it. If someone could update it, it would be great.

**Comment by Chalarangelo** [comment]
As far as I'm concerned, when we are done with updating the core functionality of the website, there will be nothing else to add/change, as it will be pretty much an HTML version of the README with enhancements. Therefore, I opted not to add any guidelines about it, as it is mostly a temporary procedure. However, it wouldn't be a problem if someone sent a PR with changes to the guidelines concerning the website. In general, people should only make changes to the web builder script and/or static parts and avoid fiddling with the CSS, unless something is terribly broken (in which case they should alter the `flavor.scss` file, recompile and PR with a proper description).

**Comment by kingdavidmartins** [comment]
@Chalarangelo I couldn't agree with you more. Going this route create's less headaches. If the code added to the builder script is acceptable and consistent it should be more than enough. All contributors have to do is recompile -> check result -> submit a PR with description

**Comment by fejes713** [comment]
> In general, people should only make changes to the web builder script and/or static parts and avoid fiddling with the CSS

I agree with @kingdavidmartins and @Chalarangelo!

**Comment by Chalarangelo** [comment]
I am (hopefully) going to update guidelines and close this and #228, based on the fact that core functionality is already implemented and we now only need maintenance for the website build process.
