### ISSUE TITLE
isPrime efficiency

### ISSUE THREAD

**Issue by hubslave** [Chalarangelo/30-seconds-of-code#297]
The for loop in the isPrime snippet only needs to test up to Math.floor(num / 2).

For example isPrime(11) only needs to check divisors up to 5.

**Comment by Chalarangelo** [comment]
Good catch, you can submit a PR with this update if you want and we would gladly merge it!

**Comment by knoblock** [comment]
Actually you can do a bit better-- just test up to Math.floor(Math.sqrt(num)).  If there are two factors, you'll find the smaller one before the square root.
