### ISSUE TITLE
[BUG]everyNth doesn't return what I'd consider the "Nth" values.

### ISSUE THREAD

**Issue by Y-Less** [Chalarangelo/30-seconds-of-code#299]
### Expected Snippet Behavior

everyNth([1,2,3,4,5,6], 2) -> [ 2, 4, 6 ]

### Current Snippet Behavior

everyNth([1,2,3,4,5,6], 2) -> [ 1, 3, 5 ]

### Possible Solution

`i % nth === nth - 1`

**Comment by Chalarangelo** [comment]
The behavior is either poorly explained or not perfectly coded, but this definitely needs a fix.
