### ISSUE TITLE
[suggestion] a faster and more concise of difference

### ISSUE THREAD

**Issue by lvzhenbang** [Chalarangelo/30-seconds-of-code#333]
const difference = (a, b) => { const s = new Set(b); return a.filter(x => !s.has(x)); };

i don't think is good. i suggest writing this：
const difference = (a, b) => a.filter(x => b.indexOf(x) === -1)
or
const difference = (a, b) => a.filter(x => !b.includes(x))

**Comment by Chalarangelo** [comment]
Discussion on this is under #335, so I'm closing the issue. Any subsequent comments should be made under the PR.
