### ISSUE TITLE
[BUG] Incorrect example for flip bind

### ISSUE THREAD

**Issue by skatcat31** [Chalarangelo/30-seconds-of-code#337]
### Description 
I'm literally about to fall asleep, more marking this so I don't forget in the morning( just woke up on keyboard)

### Expected Snippet Behavior
in `flip` snippet, use shows binding a flipped function

### Current Snippet Behavior
Function binds to context, needs a null before argument(s)

### Possible Solution
change example to be
```js
const mergePerson = mergeFrom.bind(null, a)
```

**Comment by Chalarangelo** [comment]
Send a PR, would be happy to merge this! 👍
