### ISSUE TITLE
randomHexColorCode

### ISSUE THREAD

**Issue by lencx** [Chalarangelo/30-seconds-of-code#355]
`randomHexColorCode` method using loop multiple called, a hexadecimal color value of fewer than 6 bits appears.

---
*improve:*
```js
const randomHexColor = () => {
    let n = (Math.random()*0xffffff|0).toString(16)
    return '#' + (n.length !== 6
        ? '0'.repeat(6 - n.length) + n : n)
}
```

**Comment by Pl4gue** [comment]
Thank you for the issue! You may submit a PR for that. @lencx

**Comment by lencx** [comment]
```js
const randomHexColor = () => {
    let n = (Math.random()*0xfffff|0).toString(16);
    return '#' + (n.length !== 6
        ? (Math.random()*0xf|0).toString(16) + n : n);
}
```
This does not solve the original problem, `(Math.random()*0xffffff|0).toString(16)`, there are hundreds of thousands of probability will produce `2-bit` or `1-bit` hexadecimal numbers. @Pl4gue
