### ISSUE TITLE
[BUG] Shuffle algorithm is not fair

### ISSUE THREAD

**Issue by billmei** [Chalarangelo/30-seconds-of-code#357]
### Expected Snippet Behavior
The [shuffle](https://github.com/Chalarangelo/30-seconds-of-code#shuffle) snippet should be unbiased when shuffling an array

<img width="762" alt="screen shot 2017-12-25 at 18 25 01" src="https://user-images.githubusercontent.com/2248622/34345094-13bbc0a6-e9a1-11e7-80b8-b3affc0c2f0d.png">

### Current Snippet Behavior
The current shuffling algorithm is biased.

<img width="1010" alt="screen shot 2017-12-25 at 18 21 51" src="https://user-images.githubusercontent.com/2248622/34345067-e520a036-e9a0-11e7-9bcd-1cd68ebba587.png">

Mike Bostock has a [great blog post](https://bost.ocks.org/mike/algorithms/#shuffling) about why using `.sort` with a comparator results in a biased shuffle:

> Here the comparator returns a random number between -.5 and +.5. The assumption is that this defines a random order, so sorting will jumble the elements randomly and perform a good shuffle.
> 
> Unfortunately, this assumption is flawed. A random pairwise order (for any two elements) does not establish a random order for a set of elements. A comparator must obey transitivity: if a > b and b > c, then a > c. But the random comparator returns a random value, violating transitivity and causing the behavior of array.sort to be undefined! You might get lucky, or you might not.

### Possible Solution

Replace the snippet with a Fisher-Yates shuffle.

Lodash has an example implementation of the Fisher-Yates shuffle: https://github.com/lodash/lodash/blob/master/shuffle.js

I opened a Pull Request for this: https://github.com/Chalarangelo/30-seconds-of-code/pull/358

### Discussion

I assume the spirit of this repo is to keep a collection of code snippets that are succinct, in which case it is indeed the case that a comparator shuffle is shorter, in terms of lines of code, than a Fisher-Yates shuffle, at the expense of correctness.

Thus I leave it up for discussion what tradeoff we want to prioritize in this repo: Do we want succinctness at the expense of correctness, or do we want the most correct algorithm at the expense of verbosity? My preference is for the latter (i.e. replace the snippet with a Fisher-Yates shuffle) since as far as I'm aware it's the standard shuffle implementation used everywhere.

At the very least, if you decide to keep the comparator shuffle, I'd like to see some kind of disclaimer next to it noting that it is an unfair shuffle, lest someone copy/pastes snippets from this repo without digging further into it.

**Comment by atomiks** [comment]
Mentioned here #251 

> that seems alright, but I think we should keep the previous shuffle, too. Maybe we should rename the original shuffle to randomizeOrder(and add in the description that it is not truly random) and keep your implementation as shuffle.

I think this is short as possible ES6-ified? (Keeping it pure)
```js
const shuffle =([...arr]) => {
  let m = arr.length;
  while (m) {
    const i = Math.floor(Math.random() * m--);
    [arr[m], arr[i]] = [arr[i], arr[m]];
  }
  return arr;
};
```

**Comment by Chalarangelo** [comment]
This has been mentioned at least twice before. We have decided to keep this shuffle to showcase a simple yet biased technique **and** add a Fisher Yates shuffle eventually. So far there have been no PRs submitted about this yet. If anyone can implement it properly, please submit a PR with this addition and we will merge it immediately!
