### ISSUE TITLE
[Bug] UUID Generator doesn't work in Node.js 8.9.1

### ISSUE THREAD

**Issue by KingDGrizzle** [Chalarangelo/30-seconds-of-code#376]
### Expected Snippet Behavior
It generates an UUID

### Current Snippet Behavior
It errors out.

### Possible Solution
Maybe figure out a better UUID generator using `crypto.randomBytes` or whatnot

EDIT: Reading this insanity https://gist.github.com/jed/982883#gistcomment-1615714 I see the fix would be to replace `getRandomBytes(new Uint8Array(1))` with `randomBytes(1)`

**Comment by Chalarangelo** [comment]
I haven't tested the snippet in a little while, but I trust that it won't work on my environment either. I'll see if I or someone else from the team can fix this. If you have the time and come up with a solution (like the one you mentioned), feel free to submit a PR with that fix! 👍

**Comment by KingDGrizzle** [comment]
Of course. I'll look into a patch, and submit a PR.

**Comment by skatcat31** [comment]
This should be a seperate version then, however if you're REALLY going to generate UUIDs in node you should be using the `node-uuid` package
