### ISSUE TITLE
[QUESTION] duplicate snippet in fibonacciUntilNum.md + fibonacciCountUntilNum.md???

### ISSUE THREAD

**Issue by Rob-Rychs** [Chalarangelo/30-seconds-of-code#426]
Hey all I'm just wondering what the difference is between fibonacciUntilNum.md + fibonacciCountUntilNum.md?

Looks like two different implementations with the same example code? Are they accomplishing the same thing and if so is one better?

Should one be deleted?

Thanks!

**Comment by kriadmin** [comment]
No fibonacciCountUntilNum gives you the number of fibonacci numbers till a given number. 
And fibonacciUntilNum gives you the array of fibonacci numbers until num.

**Comment by Chalarangelo** [comment]
The example was wrong, I updated to resolve this. Thanks for the heads up!
