### ISSUE TITLE
[PROPOSAL] Snippet Archive

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/30-seconds-of-code#489]
With the recent rise in academic and niche snippets, I was thinking we might want to add a snippet archive. My proposal is as follows:

People have spent time and put in a lot of effort in snippets that we might not really want, as we end up thinking they are niche/academic/outdated. But we want everyone who helps out to feel valued and some of these snippets can be pretty useful for learning certain things to some people.

Deleting snippets to de-clutter our website/README is not a problem, but I'd rather we did not throw them in the trashcan permanently. Due to that, I suggest we create a `snippets_archive` folder with snippets that didn't quite make it into the package/website/README due to the community thinking they were niche/academic or simply because they are outdated after a while (e.g. due to additions in Node's default modules or new browser features). Snippets in that folder would not be built into the package, website and README, but could still be left there for people who might want to explore some more (kinda like an easter egg). 

#### Snippets that would fall under that category (personal opinion)

- [`quickSort`](https://github.com/Chalarangelo/30-seconds-of-code#quicksort) - Showcases an algorithm, rather than an interesting technique. JS has a built-in `Array.sort()` method.
- [`speechSynthesis`](https://github.com/Chalarangelo/30-seconds-of-code#speechsynthesis) - While an interesting snippet, it's very niche and the technologies used are experimental. Not the best thing to teach a new developer, if it doesn't work consistently everywhere.
- [`JSONtoDate`](https://github.com/Chalarangelo/30-seconds-of-code#jsontodate) - Limited use-cases, the date format seems slightly outdated (based on the discussion we originally had).
- [`collatz`](https://github.com/Chalarangelo/30-seconds-of-code#collatz) - Entirely academic.
- [`factors`](https://github.com/Chalarangelo/30-seconds-of-code#factors) - Mostly academic, could do without it. I am not strongly against keeping this in the codebase, but it's long and complicated and uses outside academic code are limited.
- [`howManyTimes`](https://github.com/Chalarangelo/30-seconds-of-code#howmanytimes) - I cannot really find a lot of use-cases for this snippet, plus it does not showcase any interesting techniques.
- [`isArmstrongNumber`](https://github.com/Chalarangelo/30-seconds-of-code#isarmstrongnumber) - Pretty academic.
- [`solveRPN`](https://github.com/Chalarangelo/30-seconds-of-code#solverpn) - While a very interesting read, it is very esoteric and RPN is not used a lot these days. I see no reason why to clutter up the repo and website with such a long snippet, but I wouldn't like to remove it (this is the snippet that made me think about adding an archive to begin with).

Tell me what you think in the comments below!

**Comment by mariastervic** [comment]
A snippet archive sounds a bit unnecessary, you could just go ahead and remove all of those snippets, except `factors` which is quite useful in many scenarios.

**Comment by skatcat31** [comment]
I like the idea of an archive since we can keep around some really cool snippets that might seem a bit esoteric in most other cases, like RPN which has some cool ideas regarding state management, and another way for you to declare variables( albeit somewhat harmed readability a speed, but a cool method nonethless ).

However a re-categorization may be helpful as well in the long run

**Comment by Chalarangelo** [comment]
I see nobody actively against this, so here's what I will do:

- Add a `snippets_archive` folder where we archive snippets we do not want to throw in the trash for the reasons outlined above.
- Add a step in the cron job to rebuild it every night, so that it's up-to-date. 
- Give the folder its own README, similar to the regular one, except it will not have any tagging, as the archive is probably going to be quite small for a long time.
- Add a link at the end of the current README pointing to the archive.
