### ISSUE TITLE
Keep example OPEN

### ISSUE THREAD

**Issue by fuchao2012** [Chalarangelo/30-seconds-of-code#517]
Just a “UI" proposal.

As example is the easier way for me to understand code .

so I suggest keep "Example" open in the markdown file

**Comment by Chalarangelo** [comment]
The main reason examples are closed is to make scrolling and browsing easier, otherwise we wouldn't have the collapsible `<details>` for each example to begin with. Still, if this is something that people consider more convenient, we could implement it.

**Comment by atomiks** [comment]
Problem is that it takes up too much space when quickly scrolling/browsing them. It would be nice if you could have an option (if it was possible) to expand all examples though

**Comment by Chalarangelo** [comment]
@atomiks I do not think that Github's markdown supports this without JS, which is impossible to inject into a Markdown file.
