### ISSUE TITLE
Discussion `httpPost` footprint

### ISSUE THREAD

**Issue by skatcat31** [Chalarangelo/30-seconds-of-code#530]
The following is the current footprint of the `httpPost` snippet
```js
const httpPost = (url, callback, data = null, err = console.error) => {
```
This contains an anti pattern: unknown data inference.

Since a POST request either contains or does not contain a body, we should always make it so that the body is easily found before the functions. After all the developer should always know if they need a body, even if it's null and not sent.

Example of anti pattern:
```js
httpPost(
'https://myapi.com/permissions',
json => {
  // we have our JSON, we need to parse it
  let user = JSON.parse(json)
  if( !user.admin ) return;
    ... // insert a lot of data here
},
JSON.stringify({ user: { id: 1 } }),
error =>{
  // we didn't get our JSON of the permissions. We need to display the error here
  alert('We couldn\'t load your permissions. Please try again later')
})
```
The anti pattern makes it hard to discern where the body is and what it's for. With a glance we cannot reliably identify what body is being sent.

Example of stable pattern:
**Option 1: enforce it as the second argument always**
```js
httpPost(
`https://myapi.com/banner?delete=${group.id}`,
null,
json => {
  // we know it's only function after this, we don't need to sift further
},
error => {
  ...
})
```
```js
httpPost(
'https://myapi.com/permissions',
JSON.stringify({ user: { id: 1 } }),
json => {
  // we have our JSON, we need to parse it
  let user = JSON.parse(json)
  if( !user.admin ) return;
    ... // insert a lot of data here
),
error =>{
  // we didn't get our JSON of the permissions. We need to display the error here
  alert('We couldn\'t load your permissions. Please try again later')
})
```
With this pattern we always know that it's required, and if not present not sent. There is no hunting through lines of code to find where the data is. If it's not null we add the property before sending. One extra line of code, and an enforced null otherwise.

**Option 2: cascade up arguments**
```js
const httpPost(uri, body, cb, eh = console.error) => {
  if( typeof body == 'function' ) eh = (cb && typeof cb == 'function' ? cb : eh), cb = body, body = null
  ...
}
```
This happens if called the following way:
```js
httpPost('https://myapi.com/delete/' + user.id,
json => {
  ...
})
```

Wanted to open this to a vote for change instead of just strong arming it. Yes default and optionals are NICE, but they can actively harm developer ability, and developers are much more important to keep fast than machines. Machines can figure that out easy, a developer can't.

Should we change the footprint and optional arguments declaration to avoid the anti pattern(:+1:) or note the anti pattern(👎) ?

**Comment by Chalarangelo** [comment]
**Option 1** is the way to go. It avoids the anti-pattern, while keeping the snippet clean and easy to understand.

**Comment by skatcat31** [comment]
@fejes713 @atomiks @kingdavidmartins @Pl4gue opinions?

**Comment by skatcat31** [comment]
Since no one else has responded to this but @Chalarangelo we'll update it with the first form and a check. I'll hopefully be able to get to it soon, but I'm going to be crazy busy this week

**Comment by fejes713** [comment]
@skatcat31 @Chalarangelo I totally forgot about this 😐 . However, I do agree with Robert on this one, so you guys have my approval for updating it with the first form 👍

**Comment by skatcat31** [comment]
... Does github use `Resolves #` or `Closes #`? This should have been closed...
