### ISSUE TITLE
[FIX] Lodash Backlog ~ isPrimitive !== isObject

### ISSUE THREAD

**Issue by kingdavidmartins** [Chalarangelo/30-seconds-of-code#531]
### Description 

So as I was reviewing the Lodash backlog #100 I noticed `isPrimitive.md` was put in place for the lodash `isObject` stead. Which doesn't seem appropriate when considering `isObject` suppose to behave in the following manner

### isObject Behavior 
Returns a boolean determining if the passed value is the language type of Object.  ~ *i.e. arrays, functions, objects, etc*

### isPrimitive Behavior 
Returns a boolean determining if the passed value is primitive or not.

Which according to [MDN](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) states the following
>A primitive (primitive value, primitive data type) is data that is not an object and has no methods. In JavaScript, there are 6 primitive data types: string, number, boolean, null, undefined, symbol (new in ECMAScript 2015). 

```js
const isPrimitive = val => !['object', 'function'].includes(typeof val) || val === null;

console.log(isPrimitive(null)) // Returns : True
console.log(isPrimitive(undefined)) // Returns : True
console.log(isPrimitive('string')) // Returns : True
console.log(isPrimitive(123)) // Returns : True
console.log(isPrimitive(false)) // Returns : True
console.log(isPrimitive(Symbol(42))) // Returns : True
```

<strong>Which behaves as expected</strong> 👍 

However with Objects it doesn't 😞 ❌ & is not suppose to as you can see with the following example 

```js
const isPrimitive = val => !['object', 'function'].includes(typeof val) || val === null;

console.log(isPrimitive([1, 2, 3])) // Returns : False
console.log(isPrimitive({ a:1, b:2, c:3 })) // Returns : False
```

That is why I was confused to see `isPrimitive` replace `isObject` 😖 

I'm not suggesting removing `isPrimitive` as it is extremely valuable, but suggesting to submit a PR that fulfills  https://lodash.com/docs/4.17.4#isObject & have it reflect on the Lodash log

**Comment by Chalarangelo** [comment]
Whoops, that was my bad. So, `isPrimitive` is sort of the opposite of `isObject`, right?

**Comment by kingdavidmartins** [comment]
@Chalarangelo No worries! 😄 

To be honesty I wouldn't say the opposite, Object is also a data type. It is just not a primitive data type

As stated on MDN()
### The latest ECMAScript standard defines seven data types:
- Boolean
- Null
- Undefined
- Number
- String
- Symbol (new in ECMAScript 6)
- Object 

<strong>Six data types that are primitives:</strong> *Boolean, Null, Undefined, Number, String, Symbol (new in ECMAScript 6)*

Object is just not primitive
