### ISSUE TITLE
[BUG] section title "sdbm" is misspelled

### ISSUE THREAD

**Issue by ginhton** [Chalarangelo/30-seconds-of-code#550]
### Current Snippet Behavior

* toc
![image](https://user-images.githubusercontent.com/17196141/35020001-da83635e-fb64-11e7-8894-e55d5425e18e.png)

* text 
![image](https://user-images.githubusercontent.com/17196141/35019967-b764af04-fb64-11e7-97cf-8929606c48ed.png)

### Possible Solution

just change it. 
I write a script to find those links, but this is the only one.
```python
#!-*- coding: utf-8 -*-
import re

toc_pat = "\* \[`(\w+)`\]\(#(\w+)\)"
toc_entry = []
ancher_pat = "^### (\w+)\s?$"
ancher_entry = []
s = True

def re_test(line, pat):
  return re.match(pat, line);

def check_link():
  global s
  f = open("./README.md")
  for line in f.readlines():
    if(s and re_test(line, "---")):
      s = not s
    if(s and re_test(line, toc_pat)):
      toc_entry.append(re.match(toc_pat, line).group(2))
    if(not s and re_test(line, ancher_pat)):
      ancher_entry.append(re.match(ancher_pat, line).group(1).lower())

  for item in toc_entry:
    if item not in ancher_entry:
      print item

if __name__ == '__main__':
  check_link()
```

**Comment by skatcat31** [comment]
Comment on script: While interesting, it isn't setup to work with how our snippets are designed. Any automated push from Travis would wipe out the changes.
