### ISSUE TITLE
[BUG] tomorrow() is wrong two hours of the year

### ISSUE THREAD

**Issue by NielsLeenheer** [Chalarangelo/30-seconds-of-code#564]
The `tomorrow()` function is based on the assumption that a day is always 60 * 60 * 24 = 86400 seconds long. But it is not. Due to daylight savings time most countries have one day each year that 23 hours long and one day that is 25 hours long.

So take change from winter time to summer time in The Netherlands:
On Sunday, 25th of March 2018 at 02:00 the clock skips and hour to 03:00 and the day will be just 23 hours. So if you call the function the day before on 24th of March at 23:01 and add 24 hours, it will not arrive at 23:01 of the 25th, but instead at 00:01 of the 26th. That is not tomorrow, but the day after tomorrow.

And the change from summer time to wintertime in The Netherlands:
On Sunday, 27th of October 2018 at 03:00 the clock goes back to 02:00 and the day will be 25 hours long. So if you call the function on the 27th at 00:59 and add 24 hours, it will not arrive at 00:59 the next day, but on 23:59 of the same day.

So for two hours each year, this function will give the wrong result. For one hour it will give the same day and for one hour it will give the day after tomorrow.

Using the build-in getDate and setDate function of the Date object is safer.

```
const tomorrow = () => { 
    let t = new Date();
    t.setDate(new Date().getDate() + 1);
    return t.toISOString().split('T')[0]; 
};
```

**Comment by NielsLeenheer** [comment]
Actually the problem is worse than this.

You should not use toISOString() for this. That function converts the local time to UTC and there is no reason to assume the date in UTC time is the same as your local timezone.

Take for example:

Assume it is 09:00 in Sydney, Australia. Today it has a 11 hour timezone difference with UTC. 

````
new Date()
> Mon Jan 22 2018 09:00:00 GMT+1100 (AEDT)
````

Now if I determine the date using toISOString().

````
new Date().toISOString()
> "2018-01-21T22:00:00.000Z"

new Date().toISOString().split('T')[0]
> "2018-01-21"
````

The date is off by one day. So if I were to get the date of tomorrow and use the correct method to do that, than I would still get today as the result.

So the correct way is probably something like this:

````
const tomorrow = () => { 
    let t = new Date();
    t.setDate(new Date().getDate() + 1);
    return t.getFullYear() + '-' + String(t.getMonth() + 1).padStart(2, '0') + '-' + String(t.getDay()).padStart(2, '0')
};
````

**Comment by skatcat31** [comment]
This is a well known limitation of the date library. However the last codeblock could be updated to
```js
const tomorrow = () => { 
    let t = new Date();
    t.setDate(t.getDate() + 1);
    return t.getFullYear() + '-' + String(t.getMonth() + 1).padStart(2, '0') + '-' + String(t.getDay()).padStart(2, '0')
};
```
If you would like to PR a fix for the snippet you're more than welcome too, or if two hours for tomorrow to be off is acceptable(up time of the function would be considered 99.99%) it could also be left the same, however yes it is off tow hours a year.
