### ISSUE TITLE
[FEATURE] Internationalization

### ISSUE THREAD

**Issue by sulian** [Chalarangelo/30-seconds-of-code#569]
Do you think create international version of "30-seconds-of-code" like Sarah Drasner's [Array explorer](https://github.com/sdras/array-explorer) ?

Thanks !

**Comment by Chalarangelo** [comment]
We have discussed this previously. The idea is not unappealing to us, but there would have to be some maintainers taking care of snippets every single day, so that everything is up to date.

Currently, we have no plan to implement such a feature, but when we eventually reach a point of stability (snippets being added extremely infrequently), it could be a decent idea to do so.

**Comment by sulian** [comment]
thanks you for your response 👍 

I can help for french version.

**Comment by kriadmin** [comment]
I can help in the `hindi` version

**Comment by fejes713** [comment]
This would be awesome if we had few people to take care of that. Having something multilingual means that it has to be updated regularly not just make it once and leave it forever. 

Snippets change, descriptions do, contribution guidelines also... We would need a really hardcore maintenance team to take care of every single language out there

For now, I think we should stick to English only. Personally, I find it more interesting to learn from English resources as most of the technical words can't be well translated. 

I have no problem translating everything to Serbian, but I think it is just not worth it.

**Comment by Chalarangelo** [comment]
About 5-10k lines of text (conservative estimate) need to be translated in each language. That's a ton of work for any one person to deal with and keep an eye out on for future changes. Doesn't seem viable to me honestly.

**Comment by fejes713** [comment]
@Chalarangelo We should close this one right? 😄

**Comment by Chalarangelo** [comment]
Yep, at least for now. Maybe we can revisit this later down the line, but I'm not suepr optimistic this is doable unless we sort of stop adding stuff at some point and have a stable long-term release, which I doubt would work well with the nature of the repo.
