### ISSUE TITLE
there may be a bug in randomHexColorCode function

### ISSUE THREAD

**Issue by Ghohankawk** [Chalarangelo/30-seconds-of-code#580]
hi,i read the this code rencently, i maybe find a bug in randomHexColorCode function.

your code is 

```
const randomHexColorCode = () => {

  let n = ((Math.random() * 0xfffff) | 0).toString(16);

  return '#' + (n.length !== 6 ? ((Math.random() * 0xf) | 0).toString(16) + n : n);

};
```

in this code ,varible n, n.lengh can be little than 6, this means 1 or 2 or 3 or 4 or 5 or 6

when n.length === 1,eg, n = 5,if ((Math.random() * 0xf) | 0).toString(16) = 6,the function may return '#65',this is not 24 bits color

is am wrong ?

so this is my code 

```
   //获取24位像素的色彩
    const randomHexColorCode = () => {
        let baseF = [0, 0xf, 0xff, 0xfff, 0xffff, 0xfffff];
        let n = ((Math.random() * 0xffffff) | 0).toString(16);
        return '#' + (n.length === 6 ? n : ((Math.random() * baseF[6 - n.length]) | 0).toString(16) + n);
    };
```

thanks

**Comment by kriadmin** [comment]
@Ghohankawk @Chalarangelo   I think we can just do the following:
```js
const randomHexColorCode = () => return ((Math.random() * 0xfffff)).toString(16).replace('.','').slice(0,6)
```

**Comment by Ghohankawk** [comment]
@kriadmin yes,this is a good way,thanks a lot
