### ISSUE TITLE
Function: delay is just another name for setTimeout

### ISSUE THREAD

**Issue by ErrOrnAmE** [Chalarangelo/30-seconds-of-code#587]
```
const delay = (fn, wait, ...args) => setTimeout(fn, wait, ...args);
```

Isn't that the same as the following ?
```
const delay = setTimeout;
```

**Comment by Chalarangelo** [comment]
It is, but that way whoever is reading the snippet will not be able to easily understand the expected arguments. `delay` might not seem like much, but a lot of people are not instantly familiar with `setTimeout` so it serves a practical purpose in terms of learning for beginners.
