### ISSUE TITLE
advanced zipWith

### ISSUE THREAD

**Issue by OPY-bbt** [Chalarangelo/30-seconds-of-code#601]
```js
const zipWith = (...array) => {
  const fn = typeof array[array.length - 1] === 'function' ? array.pop() : undefined;
  const maxLength = Math.max(...array.map(a => a.length));
  return Array
    .from(
      { length: maxLength },
      (_, i) => (fn ? fn(...array.map(a => a[i])) : array.map(a => a[i])),
    );
};
```
Is there any problem with this? thanks

**Comment by Chalarangelo** [comment]
If there are no bugs or unexpected edge-cases this cannot handle, I see no reason why we shouldn't shorten the snippet.

**Comment by Chalarangelo** [comment]
@skatcat31 Any unwanted side-effects that we might be overlooking? This issue has been sitting here quietly for a while, let's deal with it.

**Comment by skatcat31** [comment]
This looks like it's a straightforward condensing using ternaries which should be fine. I can't find any code that would cause a side effect beyond what the array methods cause already

**Comment by Chalarangelo** [comment]
Ok, so I'll just commit it directly and merge it to close this issue.

**Comment by skatcat31** [comment]
In fact it can be condensed further by nesting the maxlength logic(we still need a direct reference to the function though)
```js
const zipWith = (...array) => {
  const fn = typeof array[array.length - 1] === 'function' ? array.pop() : undefined;
  return Array
    .from(
      { length: Math.max(...array.map(a => a.length)) },
      (_, i) => (fn ? fn(...array.map(a => a[i])) : array.map(a => a[i])),
    );
};
```

**Comment by skatcat31** [comment]
The only awkward part comes from the fact that we need the closure for the index position of the sub arrays or we could condense further

**Comment by Chalarangelo** [comment]
I think your version strikes a great balance between brevity and readability, let's leave it at just that for now.
