### ISSUE TITLE
[FEATURE] Super simple app to browse snippets

### ISSUE THREAD

**Issue by RCHowell** [Chalarangelo/30-seconds-of-code#608]
I threw together this Flutter app which lets you browse snippets on your phone.

Link to repo [here](https://github.com/RCHowell/seconds_of_code).

It will run on iOS and Android. All you have to do is visit [https://flutter.io](https://flutter.io) and download the framework.

**Comment by kriadmin** [comment]
@RCHowell Is it online or offline? How are new snippets added? Can you share some screenshots?

**Comment by RCHowell** [comment]
It is online. It pulls snippets from the `/snippets` folder. The only issue it has right now, is that the base64 encoding of each snippet's markdown file has newlines in it, but dartlang's base64 decoder struggles with newlines. I can look into fixing that today.

![](https://i.imgur.com/xLVr0Xm.png)

![](https://i.imgur.com/98Gd9hq.png)

**Comment by RCHowell** [comment]
Just fixed the newline issue. See screenshot.
![](https://i.imgur.com/blyXMoF.png)

**Comment by Chalarangelo** [comment]
I think we could probably link to download links for the app from the README, in case anyone wants to use it. It looks nice and simple, so I expect that a lot of people will find it a convenient alternative to the website and README.

**Comment by Pl4gue** [comment]
Just left you an email @RCHowell.

**Comment by fejes713** [comment]
@RCHowell Amazing work 🔥

**Comment by bboydflo** [comment]
@RCHowell there are still some issues with `>` and `<` from what I can see in the screenshot. Nice work by the way!

**Comment by Pl4gue** [comment]
Closing this til further notice.
