### ISSUE TITLE
[not BUG or FEATURE]Question about sortedLastIndex and sortedLastIndexBy

### ISSUE THREAD

**Issue by Shenmin-Z** [Chalarangelo/30-seconds-of-code#612]
Not a bug since it's working; not a feature as it's not something new.
For sortedLastIndex and sortedLastIndexBy, there is
```
const index = arr
    .map((val, i) => [i, val])
    .reverse()
    .findIndex(el => (isDescending ? n <= el[1] : n >= el[1]));
```
I wonder what `map((val, i) => [i, val])` does, seems like that piece can be done without it, like
```
const index = arr
    .reverse()
    .findIndex(el => (isDescending ? n <= el : n >= el));
```

Or maybe the intention was to use `find` instead of `findIndex`?

**Comment by Chalarangelo** [comment]
The mapping is done in order to store the original index alongside the value so that the original index (not the one in the reversed array) can be returned.

**Comment by Shenmin-Z** [comment]
I mean I know what `map((val, i) => [i, val])` does, but that mapped result is not used later in the code. I see `el[1]` which is value, but I don't anything like `el[0]`.

**Comment by Chalarangelo** [comment]
Whoops, that does look like a typo on our part, let me check it out more carefully (as there might be a handful of snippets affected by this) and get back to you in the morning!

**Comment by Chalarangelo** [comment]
You were absolutely right, that was some leftover code from elsewhere, it should be all cleaned up now. Thanks for reporting this!

**Comment by Shenmin-Z** [comment]
Glad could help!
