### ISSUE TITLE
[BUG] Website is difficult to use on mobile.

### ISSUE THREAD

**Issue by kriadmin** [Chalarangelo/30-seconds-of-code#615]
## [BUG]  The icon on left corner to open search(on mobile)  is not visible when we are not on top. 
I am not a CSS ninja so can't suugest something perfect  but we can use `position : fixed`? Maybe @atomiks can suggest a better fix.

**Comment by Chalarangelo** [comment]
Cannot reproduce neither on mobile or desktop with mobile view in browsers. The icon stays on the top left corner as expected. Can you post screenshots and device information so we can reproduce the issue?

**Comment by kriadmin** [comment]
https://ufile.io/7iv2e See this screen recording. Sorry but github doesn't support uploading .mp4 files and the late response was due to time differneces.

**Comment by Chalarangelo** [comment]
That is an old device that does not support `position: sticky`. Normally, I would not bother to change this, but seeing as the header is fixed to the top anyways, this might be worth checking out. Let me see what I can do.

**Comment by NguoiThuaKe** [comment]
Nguoithuake.1905@github.com
