### ISSUE TITLE
Array method constistency in descriptions

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/30-seconds-of-code#62]
Right now there are inconsistencies when referencing `Array` methods, like `reduce()`, in snippet descriptions. Sometimes they are referenced as `Array.reduce()` and other times as `reduce()`. The preferred option would be to refer to them as `Array.reduce()`, so if anyone can get to that and fix it, I would appreciate it.

(Methods that need to be dealt with right not are `sort()`, `map()`, `reduce()` - I think these are all, but I might be forgetting something).

**Comment by piyuesh-dev** [comment]
I've never made contribution here, so I'd like to take this up. Just clarifying reduce(), map(), sort() should be prefixed by Array. . right ?

**Comment by Chalarangelo** [comment]
@piyuesh-dev Exactly. All new contributors are welcome. Make your changes to the individual snippet files, not README. I will compile README afterwards. Thanks a ton for helping out!

**Comment by piyuesh-dev** [comment]
Ok thanks, I'll fork it & submit pull after few changes.

**Comment by piyuesh-dev** [comment]
I've submitted a pull request at https://github.com/Chalarangelo/30-seconds-of-code/pull/70
