### ISSUE TITLE
[FEATURE] Update isAnagram function

### ISSUE THREAD

**Issue by Orangalo** [Chalarangelo/30-seconds-of-code#620]
## [FEATURE] isAnagram function could be done with O(n), by utilising the fundamental theorem of arithmetic
**Category:** String
### Description
The current algorithm for isAnagram uses a `normalize` function, which uses .sort(), whose time complexity is O(n*log(n)).
A more efficient algorithm is as follows:
1. 'Replace' every `a` with `2`, `b` with 3, `c` with 5, `d` with 7, etc. (unique prime number for each letter)
2. For each word, multiply out the values of each letter
3. Compare the products of each word

This will work because by the fundamental theorem of arithmetic the prime factorisation of a number is unique. Because multiplication is abelian, the order won't matter.

For example, consider 'abcd' and 'dabc'. For the first, we get `2*3*5*7=210` and for the second we also of course get `7*2*3*5=210`.

Such an algorithm would only iterate once on every word, making the algorithm O(n).

**Comment by Chalarangelo** [comment]
I think that the performance benefit far outweighs the readbility of the snippet. We are already using a regular expression to remove a lot of other things, which is definitely quite slow. Plus, the snippet will only take a long time for strings with characters counts in the hundreds or thousands. I think it's an unnecessary change. However, I would like some opinions on this. 
@kingdavidmartins @fejes713 @skatcat31 @atomiks

**Comment by fejes713** [comment]
> I think that the performance benefit far outweighs the readability of the snippet.

Enough said. Every snippet is meant to be understandable in under 30 seconds. We shouldn't touch this. 

Thanks for opening an issue anyways! 👍

**Comment by skatcat31** [comment]
But the archive.....
