### ISSUE TITLE
A simple way to `findLastIndex`

### ISSUE THREAD

**Issue by tangweikun** [Chalarangelo/30-seconds-of-code#621]
## [FEATURE] A simple way to `findLastIndex`, return `-1` if not find.
**Category:** Array
### Possible Solution
```js
const findLastIndex = (arr, fn) =>
  arr.length - 1 - ~~arr.reverse().findIndex(fn)
```

**Comment by Chalarangelo** [comment]
While shorter, this certainly feels hacky and is not easy to understand. The technique showcased in the original code is far more useful and can come in handy as an introduction to using `Array.prototype` methods. Thanks for the suggestion anyways!
