### ISSUE TITLE
[BUG] `isSorted` miss some test case

### ISSUE THREAD

**Issue by tangweikun** [Chalarangelo/30-seconds-of-code#624]
## [BUG] `isSorted` miss some test case
**Category:** Array
### Description 
```js
isSorted([2,2,1]) // 0, expect return -1
isSorted([1]) // 1, maybe should claim length of input more than 1
isSorted([]) // undefined
```

**Comment by Chalarangelo** [comment]
- `isSorted([1])` is entirely correct. Single element arrays are technically sorted either way.
- `isSorted([])` is also fine as it is an empty array, so it's sort order is `undefined`.
- `isSorted([2,2,1])` is kind of problematic, though, we should look into it.

**Comment by tangweikun** [comment]
Is it make sense `isSorted([1])` return `-1`?

**Comment by Chalarangelo** [comment]
`isSorted([1])` would be correct in returning either `1` or `-1` as it sorted both ways technically speaking.

**Comment by tangweikun** [comment]
There is one way to fix the bug, but the code is not elegane
```js
const isSorted = arr => {
  let pre = arr[0]
  let direction = undefined
  for (let i = 1; i < arr.length; i++) {
    if (direction * (pre - arr[i]) > 0) return 0
    if (direction === undefined) {
      if (pre > arr[i]) direction = -1
      if (pre < arr[i]) direction = 1
    }
    pre = arr[i]
  }
  return pre === undefined ? 1 : direction
}
```
