### ISSUE TITLE
[FETURE] Refactor `maxN`

### ISSUE THREAD

**Issue by tangweikun** [Chalarangelo/30-seconds-of-code#625]
## [FEATURE] `[...arr]` is unnecessary, just use `arr`
**Category:** Array
### Possible Solution
```js
const maxN = (arr, n = 1) => arr.sort((a, b) => b - a).slice(0, n);
```

**Comment by Chalarangelo** [comment]
Please read the snippet description:
> Use Array.sort() combined with the spread operator (...) to create a shallow clone of the array and sort it in descending order. 

Therefore spreading the array is necessary as it creates a shallow clone of it and does not mutate the original array.
