### ISSUE TITLE
Questions about `sortedIndex` and `sortedLastIndex`

### ISSUE THREAD

**Issue by HowardTangHw** [Chalarangelo/30-seconds-of-code#629]
**sortedIndex**
Returns the `lowest` index at which value should be inserted into array in order to maintain its sort order

**sortedLastIndex**
Returns the `highest` index at which value should be inserted into array in order to maintain its sort 
order.

but 
```javascript
sortedIndex([5, 3, 2, 1], 4); // 1

sortedLastIndex([5, 3, 2, 1], 4); // 0

```

Is the answer correct? Or is my understanding of the mistake

**Comment by Chalarangelo** [comment]
`sortedIndex` is correct. `sortedLastIndex` *should* return the same, but it does not seem to do so. Let me check this out.

**Comment by HowardTangHw** [comment]
const sortedLastIndex = (arr, n) => {
  const isDescending = arr[0] > arr[arr.length - 1];
  const index = arr.reverse().findIndex(el => (isDescending ? n <= el : n >= el));
  return index === -1 ? 0 : arr.length - index;
};

**Comment by Chalarangelo** [comment]
I remember distinctly trying to use this exact code and breaking for certain cases, while `-1` did somehow solve problems. I'm quite certain I missed something at some point. I will need some edge cases to test this on, but this will certainly be fixed soon.
