### ISSUE TITLE
[BUG] [WEBSITE] Disclaimer about production use

### ISSUE THREAD

**Issue by sorin-davidoi** [Chalarangelo/30-seconds-of-code#635]
### Expected Snippet Behavior

Some snippets have performance issues that should come with a disclaimer:
 - [deepFlatten](https://30secondsofcode.org/#deepflatten) creates an intermediary array at each recursion step. If the array is large and deeply-nested, this will lead to an increased memory consumption (if it runs on the main thread it will block it after the function finishes execution due to the garbage collection kicking in). Maybe point to something like the first snippet [from here](https://stackoverflow.com/a/34757676), which does not exhibit this problem.
 - [runAsync](https://30secondsofcode.org/#runasync) creates a WebWorker **each time it's called** - there should be a warning not to call this function from inside a `map`, `forEach` or any kind of loop.
 - [createElement](https://30secondsofcode.org/#createelement) - causes the browser to parse the string during each call. Using a [`template`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) is a better solution if this function is called multiple times with the same argument.

### Current Snippet Behavior

No warning that using some snippets in a production environment might cause serious performance issues.

### Possible Solution
Display a warning (either next to the snippet or when the "Copy to clipboard" button is pressed).

**Comment by Chalarangelo** [comment]
Literally everywhere on the repository users are warned about the fact that the code is not production-ready and merely a learning resource. Adding this disclaimer to every snippet is kind of pointless, however there might be some more prominent places to display the **not production-ready** notices on the website. I'm closing the issue as the individual snippets are irrelevant to the way we are going to solve this, but I am going to deal with it during the weekend to make sure the website has the proper warnings for users who do not visit the repository itself.

**Comment by sorin-davidoi** [comment]
> Literally everywhere on the repository users are warned about the fact that the code is not production-ready and merely a learning resource.

My bad, I should have mentioned that I was referring to the website and not the repository.

> I am going to deal with it during the weekend to make sure the website has the proper warnings for users who do not visit the repository itself.

Thank you.

**Comment by skatcat31** [comment]
Should this be closed before the website is updated? I know it's on the schedule you keep @Chalarangelo but it might be a good idea to keep it open until then just as a reminder
