### ISSUE TITLE
BUG-Attempt

### ISSUE THREAD

**Issue by timurcatakli** [Chalarangelo/30-seconds-of-code#638]
Hi there, about attempt. Shouldn't  return function have the args as a spread. See below please. If so I can make a pr.

Thanks,
```const attempt = (fn, ...args) => {
  try {
    return fn(...args);
  } catch (e) {
    return e instanceof Error ? e : new Error(e);
  }
};

const testFn = (a, b) => {
  return a + b
}
const elements = attempt(testFn, 12, 3)
console.log(elements) // return 15
````

**Comment by Chalarangelo** [comment]
Indeed it should be `return fn(...args)` instead of `return fn(args)`. Thanks for noticing that! You can submit a PR as soon as you want and we will get right onto it!
