### ISSUE TITLE
[GUIDELINES] Order of Decleration Change to Contribution Guidelines

### ISSUE THREAD

**Issue by skatcat31** [Chalarangelo/30-seconds-of-code#647]
Since this isn't something that even fits into our usual Snippet Issue Format since it's a proposed change poll to the Guidelines on Snippet Structure and Deceleration Order for function footprints, I'm going to just write out the current notices and propose a few solutions to look into:

# Current Snippets Declaration Order is Not Consistent
We have several snippets that all implement different types of footprints. This has lead to some inconsistency in what a function looks like. We should come up with a new rule in the contribution guidelines so that in the future each snippet will have a consistent footprint:

```js
// Callback order
const func1 = (data, callback) => callback(data)
const func2 = (callback, data) => callback(data)

// Library/Applicable order
const lib1 = (library, data) => Object.keys(library).reduce(RULEFN, {})
const lib2 = (data, library) => Object.keys(library.reduce(RULEFN, {})
```

We had this discussion before with the `simpleHTTP` discussion however that never actually led to a change to the contribution guidelines. While we have the Adapter category and the bind function to allow us to transform any snippet to another form, we MIGHT want to declare what default footprint our functions should have. Especially since there are so many prior arts at this point we want to declare where we stand on it to avoid low quality or confus(ed/ing) submissions( see https://github.com/Chalarangelo/30-seconds-of-code/pull/646 for an example of it being unclear and the submitter making a decision due to the ambiguity ).

I'm a fan of the way Ramda does things with Data last since it allows really easy library generation( at the sacrificing of debugability, it increases maintainability ), but I know not every one is, especially since it can make single use callbacks VERY confusing to read since you have to go through the function body before seeing what the function is applying too.

As such we should vote on the footprint Order of Operations so that when a snippet is submitted it will be in a form we can all agree will lead to faster reading and implimentation( see [API consistency](https://www.linkedin.com/pulse/from-back-end-robert-mennell/) and [library generation](https://www.linkedin.com/pulse/fun-programming-robert-mennell) for examples )

Just like PEMDAS, we should know how our functions will apply. Thankfully these have parts!

 - Data  
The Data that will be operated on
 - Function  
The Function(s) that will be applied to the data
 - Libraries  
The Objects/Hashes/Arrays( data constructs ) used for certain operations in the Function or Snippet Logic

Possibly Footprint:

### FLD
`(Functions, Libraries, Data)`

Advantages:

 - VERY friendly to library generation
 - Prior art from Ramda

Disadvantages:

 - VERY confusing for one off closures since you need to read the function contents BEFORE seeing the data applied too

### FDL
`(Functions, Data, Libraries)`

Advantages:

 - .... Uh?

Disadvantages:

 - Difficult to apply to library generation in cases where you want different functions at run time with the same library
 - VERY confusing for one off closures since you need to read the function contents BEFORE seeing the data applied too

### LFD
`(Libraries, Functions, Data)`

Advantages:

 - VERY friendly to applicative functions
 - Prior Art from Express( Data comes later as request come in )

Disadvantages:

 - Difficult to apply to library generation in cases where you want different hashes

### LDF
`(Library, Data, Function)`

Advantages:

 - Very easy to read inline with closures, you know what the data being applied to is and what library will be modifying it

Disadvantages:

 - HORRIBLE for library generation without am Adapter

### DLF
`(Data, Library, Function)`

Advantages:

 - So easy to read for simple closures

Disadvantages:

 - Library generation requires a `Flip`

### DFL
`(Data, Function, Library)`

Advantages:

 - ... Uh? # 2

Disadvantages:

 - Confusing Footprint with no prior art

**Comment by Chalarangelo** [comment]
The more sensible thing seems like `LDF`. Libraries come first (which is what happens in most of our snippets anyways), data afterwards and functions/callbacks last. The issue with that is the need for an adapter of which we have plenty (and this is also a good way to introduce people to them). I also think there should be some space to add exceptions to the rules if they are well-justified, although the guidelines should only state the general rule and we can handle exceptions as snippets come in or even retroactively.

**Comment by skatcat31** [comment]
`LDF` or `DLF` seem like the most readable, I agree. An with how easy closures are to change order, it would make it just that easy to adapt by making a `middleMan` function(s)(an adapter for a specific use case meant to be used with your libraries specific design patterns to adhere to other library design patterns on execution)

**Comment by Chalarangelo** [comment]
@skatcat31 Regardless of the final decision, `middleMan` sounds like a cool adapter. We could use the implementation if you have the time! 😉

**Comment by skatcat31** [comment]
`middleMan` is a class of adapter

`middleManRamda` would be one:

```js
const toRamda => fn => curry((F,L,D) => fn(L,D,F)) // Auto Curry the function and change the footprint to a Ramda like one
```

**Comment by skatcat31** [comment]
Updated the subject. If this doesn't get any more votes or comments in the next couple of days on Sunday I'll open a larger issue after doing a PR for updating the guidelines. Current choice is going to be `DLF` for simple adaption to `Data Last` footprint using `flip`

**Comment by mariastervic** [comment]
I would go with *LDF*. It's definetely the most readable format.

**Comment by Chalarangelo** [comment]
@skatcat31 Having intimate knowledge of our codebase so far, what would be the format the requires the least amount of changes to snippets? I'm asking as this change could affect a lot of people that visit the website and repo, so we have to consider these implications as well.

**Comment by skatcat31** [comment]
@Chalarangelo ooh that's a good point... We'll have to do an analysis...

@mariastervic care to clarify a bit more? As I look at the two I don't care too much either way but I'm curious why people consider one more readable than the other(I only was defaulting to `DLF` for extension purposes)

**Comment by Chalarangelo** [comment]
I think without a statistical analysis of our codebase, we cannot really proceed to make any changes. We could analyze which snippets have been altered multiple times moving from one format to the other, but 300+ snippets and 650ish issues are quite a tall order, so let's not do all of that and just stick to what kind of format we are using so far.

**Comment by skatcat31** [comment]
@Chalarangelo I think it still might be useful to add to the GuideLines for snippets coming in and we can possibly look at making a modification to the package generator to create adapted snippets while building under a `${snippetName}LDF` name so that we don't break legacy and give people a compatible interface with documentation so that in the future it doesn't become a problem

**Comment by skatcat31** [comment]
plus it'd give us a depreciation and sunset plan, allowing people to use an older version if they don't need newer features of the package, and eventually coming to a consistent footprint. If done correctly it should lead to extremely little breacking

**Comment by Chalarangelo** [comment]
I'm gonna close due to inactivity and the discussion being inconclusive. After all, this would require extensive refactoring and changing tests etc., so we might as well skip it for a while, until we figure out some other stuff first.
