### ISSUE TITLE
[FEATURE] castArray for null and undefined => []

### ISSUE THREAD

**Issue by emelendez** [Chalarangelo/30-seconds-of-code#654]
## [FEATURE] castArray for null and undefined => []
**Category:** new feature for "castArray"
### Suggestion
instead of: 
`const castArray = val => (Array.isArray(val) ? val : [val]);`
more complete:
`const castArray = val => Array.isArray(val) ? val : val == null ? [] : [val];  `

examples:
```
castArray('foo'); // ['foo']
castArray([1]); // [1]
castArray(null); // []
castArray(undefined); // []

```
so includes case of "null" or undefined values which results in an empty array. Also no need of parenthesis in code.
I have to include this because 90% of cases you castArray(theunexpectedresultofthingelse()).map(...) and is useful in resulting data null or undefined from theunexpect...()

**Comment by skatcat31** [comment]
I'm closing this issue since we want to preserve comparison code and empty array indexes as expected and due to lack of activity
