### ISSUE TITLE
[BUG] Object deepClone has a bug when property is an array

### ISSUE THREAD

**Issue by rannuo** [Chalarangelo/30-seconds-of-code#658]
### Expected Snippet Behavior
```js
// const deepClone = 30secondsofcode's deepClone;

const a = { foo: 'bar', arr: ['a', 'b'] };
const b = deepClone(a); 
b // { foo: 'bar', arr: ['a', 'b'] }
```

### Current Snippet Behavior
```js
// const deepClone = 30secondsofcode's deepClone;

const a = { foo: 'bar', arr: ['a', 'b'] };
const b = deepClone(a); 
b // { foo: 'bar', arr: { '0': 'a', '1': 'b'} }
```

### Possible Solution
add Array.isArray and to clone array

**Comment by skatcat31** [comment]
Confirmed behavior. If you'd like to author a fix to the snippet a pull request is welcome.

All that would need to be changed is to add a check if the "object" is an Array using `Array.isArray` and if so have different handling logic( Array.from(deepClone(object)) or the like)

**Comment by skatcat31** [comment]
I feel like this should be mentioned: Array.from will work as long as a length property is put into the Object(doable by checking if `Array.isArray(obj) ? (clone.length = obj.length) && Array.from(obj)` on the returned value
