### ISSUE TITLE
[BUG] "Not production ready" impacts users

### ISSUE THREAD

**Issue by pmw57** [Chalarangelo/30-seconds-of-code#683]
Currently with "WARNING: Snippets are not production ready." people are tempted to look at the code, are discouraged from looking at any of the code, for fear that the snippets aren't going to be useful.

I personally ignored this project because of that warning, and only on being reminded about it did I stop to think about why I was ignoring it.

I recommend that the project-wide warning be removed as a global warning, and be added instead to the relevant snippets that are likely to impact production.

**Comment by Chalarangelo** [comment]
Thanks for the suggestion. Many of the snippets are not really production-ready, meaning there are edge-cases and performance issues with them, if users want to do something that we may not have foreseen. This is in contrast with a library like Lodash, which has been built and bundled for production. 

However, the criticism that the warning might discourage users is a valid one. I already migrated our tests from Tape to Jest yesterday to make the testing more robust and allow for more extensive snippet testing later down the line. Adding more tests for snippets should be one of the steps we take to ensure snippet quality and production-readiness. I'd really like for the community to pitch in and help out by adding more tests and setting them up so we can validate which snippets are ready for production.

**Comment by Chalarangelo** [comment]
**Update:** After a lot of testing and some evaluation of the code, I believe we can change the site-wide disclaimer into more of a note that some snippets are not yet optimized for production. Disclaimers for individual snippets are still there and we might add a few more over time to address more issues that we uncover, but I think this issue is not gonna bother anyone anymore.
