### ISSUE TITLE
[FEATURE] Arrray wide equality snippet

### ISSUE THREAD

**Issue by Berkmann18** [Chalarangelo/30-seconds-of-code#700]
## [FEATURE] _All equal check on values of an array_
**Category:** Array
### Description 

Would an allEqual function that would check if all the values of an array are equal be worth putting on this repo?
I found this example [here](https://stackoverflow.com/a/35568895/5893085):
```js
const allEqual = arr => arr.every(val => val === arr[0])
```
And I couldn't find anything that would do the same job on the list of this repo.

**Comment by Chalarangelo** [comment]
This seems like an adequate beginner snippet, so why not? You can submit a PR adding the snippet to the project.

**Comment by Berkmann18** [comment]
Okay, will do.

**Comment by Berkmann18** [comment]
Done.
Am I correct in assuming that the docs are automatically generated?
