### ISSUE TITLE
[TESTS] Add unit tests for deepFreeze

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/30-seconds-of-code#728]
As a follow-up to #721, we should add some unit tests for `deepFreeze`. I went ahead and merged the PR, as the snippet definitely works, but we need to add a few tests to ensure its quality in the future.

**Comment by Siarhei-Zharnasek** [comment]
@Chalarangelo @skatcat31 
https://github.com/Chalarangelo/30-seconds-of-code/pull/742 will resolve this issue
