### ISSUE TITLE
Snippets suggestions backlog

### ISSUE THREAD

**Issue by elderhsouza** [Chalarangelo/30-seconds-of-code#81]
Hey all!

The project is looking great! We now believe that the idea is trying to demistify and get really deep into the implementation of commonly used snippets.
We think that we can look to really popular libs like lodash for example and try to implement some of the utilities by hand, no copy-pasting, just to have a fun and educative experience.

Here's a list of suggestions of utilities we could implement next:
https://lodash.com/docs/4.17.4#groupBy
https://lodash.com/docs/4.17.4#orderBy
https://lodash.com/docs/4.17.4#pick
https://lodash.com/docs/4.17.4#endsWith

**Comment by kingdavidmartins** [comment]
Hey @elderhsouza 

Here's a list of the following suggestions so far attached with their respective PR if a PR was created 

- [ ]  https://lodash.com/docs/4.17.4#groupBy | PR: #85 
- [ ]  https://lodash.com/docs/4.17.4#orderBy 
- [ ]  https://lodash.com/docs/4.17.4#pick | PR: #87 
- [ ]  https://lodash.com/docs/4.17.4#endsWith

**Comment by Chalarangelo** [comment]
Let's start with an unorganized list of all the things we want to get added, then we can decide if it's long enough to need sorting based on libraries, which I doubt. At the pace that things are being added, we will get most of the things we want implemented before we manage to complete writing the backlog. 

As soon as I manage to leaf through all the PRs and issues, I will start getting a few extra things added in, which have been delayed (natural sort, an observer pattern, random string etc.).

**Comment by Chalarangelo** [comment]
Should we close this and move the conversation to #100?

**Comment by elderhsouza** [comment]
@Chalarangelo Yes.
