### ISSUE TITLE
Categorize Snippets

### ISSUE THREAD

**Issue by meetzaveri** [Chalarangelo/30-seconds-of-code#94]
### Problem 
Day by day there are more snippets created which in future will led to unclassified structure. When user wants to search a snippet of specific area/category, then he/she would come across major data repository.

### Solution
See there are many ways to categorize these snippets by looking code, we might think the main area which it lies in.

Provided Example :
- Category : Array (all snipppets that has dealt with Array.prototype methods )
- Category : Math (all snipppets that has dealt with Math functions)
- Category : String (all snipppets that has dealt with String.prototype methods )

### Effects
This would lead to classified structure consisting all areas with their sub-repositories. When user comes to visit `README.md` file, then it will be easy to search snippet falling in to respective category.

**Comment by Chalarangelo** [comment]
This was discussed on [gitter](https://gitter.im/30-seconds-of-code/Lobby) yesterday. In all honesty, we are looking into adding an extra script to the package that will list all snippets, so we can tag them manually. This will be super helpful and not raise the barrier of entry for new contributors.

I will eventually get around to writing that script, but it will take some time, as there's a ton of things I need to deal with first.

**Comment by meetzaveri** [comment]
@Chalarangelo That's crushing idea to classify by help of tag name and will benefit to new contributors who wouldn't have to do it manually

**Comment by Chalarangelo** [comment]
Tagging is now live, it is semi-manual, but untagged snippets will not be compiled into the README, so we can have in-transit snippets if we need to. You can check the current tag stats and see what's missing by running `npm run tagger`.
